# Generated by Django 4.1.1 on 2022-10-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField(max_length=250)),
                ('major', models.CharField(max_length=20)),
                ('graduationYear', models.IntegerField()),
            ],
        ),
    ]
