# Generated by Django 4.1.1 on 2022-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
