# Generated by Django 4.1.1 on 2022-10-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
